### ISSUE TITLE
改行を挿入

### ISSUE THREAD

**Issue by c0a2103365** [c0a21065a6/ProjExD#10]
https://github.com/c0a21065a6/ProjExD/blob/b8533d25259d7a8161dd26670cec00168d6d0654/ex04/dodge_bomb.py#L166

他のif文などが2行改行されているので、統一して2行分改行したほうがいいと思います。

**Comment by c0a21065a6** [comment]
ゴールに関するプログラムをコメントアウトしたため申し訳程度に改行しました
