### ISSUE TITLE
デバッグ用のfor文について

### ISSUE THREAD

**Issue by Ryo-Miyakawa** [c0a21065a6/ProjExD#2]
https://github.com/c0a21065a6/ProjExD/blob/531e79bbf54fc2cdc7d1c288f03424fd30335e5a/ex01/al_game.py#L17

デバッグ用のfor文の中身が表示されるようになっているので、コメントアウトしたほうが良い

**Comment by c0a21065a6** [comment]
Thanks

**Comment by c0a21065a6** [comment]
直しましたありがとうございました

**Comment by c0a21065a6** [comment]
再修正しました
