### ISSUE TITLE
数値について

### ISSUE THREAD

**Issue by Ryo-Miyakawa** [c0a21065a6/ProjExD#5]
https://github.com/c0a21065a6/ProjExD/blob/5746b6d656d2c99d1e56bef4ba03f589931f3066/ex02/calc.py#L22

数値はあらかじめ変数に置いたほうが、コードを変えるときに楽になると思う。

**Comment by c0a21065a6** [comment]
この100は"%"が入力された場合の処理なので数字が変わることはないです。
そのため偏すにおく必要は無いと判断しました。

**Comment by Ryo-Miyakawa** [comment]
了解しました。

**Comment by c0a21065a6** [comment]
ご指摘ありがとうございました。
